services:
  ros2_container:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: ros2_container
    shm_size: "1gb"
    environment:
      VNC_RESOLUTION: "1280x720"
      LIBGL_ALWAYS_SOFTWARE: "1"
      TURTLEBOT3_MODEL: "burger"
      ROS2_CONTROL_PORT: "8001"
    ports:
      - "6080:6080"
      - "8001:8001"
    volumes:
      - "../..:/workspaces/btgen:rw"
    tty: true
    stdin_open: true

  ros2_container-gpu:
    profiles: ["gpu"]
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: ros2_container-gpu
    shm_size: "1gb"
    environment:
      VNC_RESOLUTION: "1280x720"
      LIBGL_ALWAYS_SOFTWARE: "0"
      NVIDIA_VISIBLE_DEVICES: "all"
      NVIDIA_DRIVER_CAPABILITIES: "all"
      TURTLEBOT3_MODEL: "burger"
      ROS2_CONTROL_PORT: "8001"
    ports:
      - "6081:6080"
      - "8002:8001"
    volumes:
      - "../..:/workspaces/btgen:rw"
    gpus: all
    tty: true
    stdin_open: true

